[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  extra_args = [ "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  extra_args = [ "-lparachain=debug" ]

[[parachains]]
id = 4292
chain = "contracts-parachain-local"

  [[parachains.collators]]
  name = "collator01"
  command = "./target/release/parachain-contracts-node"
  args = ["--log=debug"]

  [[parachains.collators]]
  name = "collator02"
  command = "./target/release/parachain-contracts-node"
  args = ["--log=debug"]

